// src/app/(dashboard)/dashboard/mis-tareas/page.tsx
"use client";

import { useSession } from "next-auth/react";
import {
  CheckSquare, Package, Truck, Store,
  AlertTriangle, Clock, CheckCircle2, Calendar,
} from "lucide-react";
import { SlaEstado, SLA_COLOR, SLA_LABEL, calcSla, diasRestantesSla } from "@/lib/sla";
import { urgencia } from "@/lib/transporte";
import { horasDesde } from "@/lib/tienda";
import { Badge, EmptyState, ModuleHero } from "@/components/ui";
import { AutoRefreshIndicator } from "@/components/ui/AutoRefreshIndicator";
import { useAutoRefresh } from "@/hooks/useAutoRefresh";
import { useApi } from "@/hooks/useApi";
import Link from "next/link";
import { getModuleCssVars } from "@/lib/moduleTheme";

// Forma de los items que devuelve GET /api/mis-tareas.
interface TareaNovedad {
  id: string; plu: string; posicion: string; estado: string;
  fabricante: string | null; asignadoA: string | null;
  fechaCompromiso: string | null; esPropio: boolean;
}
interface TareaGuardado {
  id: string; clientId: string; documento: string; ubicacion: string;
  estado: string; fecha: string; nota: string | null; tipo: string | null;
}
interface TareaGuardadoTienda {
  id: string; despachoId: string; nota: string | null; createdAt: string;
  documento: string; clienteNombre: string; centroCostos: string; numeroCajas: number | null;
}
interface TareaDespacho {
  id: string; centroCostos: string; numeroDocumento: string; clienteNombre: string;
  estado: string; fechaCreacion: string; fechaEntregaComprometida: string | null; createdAt: string;
}

interface MisTareas {
  novedades: TareaNovedad[];
  guardados: TareaGuardado[];
  guardadosTiendaPendientes: TareaGuardadoTienda[];
  despachosTienda: TareaDespacho[];
  notifNoLeidas: number;
}

// ── Tarjeta de tarea individual ───────────────────────────
function TareaCard({ titulo, sub, badge, badgeColor, href, tiempo, alerta }: {
  titulo: string; sub?: string; badge?: string; badgeColor?: string;
  href: string; tiempo?: string; alerta?: boolean;
}) {
  return (
    <Link href={href} style={{ textDecoration: "none" }}>
      <div
        style={{ display: "flex", alignItems: "flex-start", gap: 12, padding: "12px 16px", background: "var(--surface)", border: `1px solid ${alerta ? "color-mix(in srgb, var(--error) 30%, transparent)" : "var(--border)"}`, borderRadius: 10, transition: "box-shadow .12s", cursor: "pointer" }}
        onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.boxShadow = "var(--shadow-md)"; }}
        onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.boxShadow = "none"; }}
      >
        {alerta && <AlertTriangle size={14} color="var(--error)" style={{ flexShrink: 0, marginTop: 2 }} />}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{titulo}</div>
          {sub && <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 2 }}>{sub}</div>}
        </div>
        <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 4, flexShrink: 0 }}>
          {badge && <span style={{ fontSize: 10, fontWeight: 700, padding: "2px 7px", borderRadius: 20, background: (badgeColor ?? "var(--muted)") + "18", color: badgeColor ?? "var(--muted)" }}>{badge}</span>}
          {tiempo && <span style={{ fontSize: 10, color: "var(--faint)", fontFamily: "var(--mono)" }}>{tiempo}</span>}
        </div>
      </div>
    </Link>
  );
}

// ── Sección colapsable ────────────────────────────────────
function Seccion({ icon, title, count, color, children }: {
  icon: React.ReactNode; title: string; count: number; color: string; children: React.ReactNode;
}) {
  return (
    <div style={{ marginBottom: 20 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
        <div style={{ width: 28, height: 28, borderRadius: 7, background: color + "14", display: "flex", alignItems: "center", justifyContent: "center", color, flexShrink: 0 }}>{icon}</div>
        <span style={{ fontSize: 13, fontWeight: 700, color: "var(--text)" }}>{title}</span>
        <span style={{ fontSize: 12, fontWeight: 700, padding: "1px 8px", borderRadius: 20, background: count > 0 ? color + "18" : "var(--surface2)", color: count > 0 ? color : "var(--muted)", fontFamily: "var(--mono)" }}>{count}</span>
      </div>
      {count === 0 ? (
        <div style={{ padding: "12px 16px", background: "var(--surface2)", borderRadius: 10, fontSize: 12, color: "var(--muted)", textAlign: "center" }}>
          <CheckCircle2 size={14} style={{ verticalAlign: "middle", marginRight: 6 }} />Sin tareas pendientes
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>{children}</div>
      )}
    </div>
  );
}

function fmtFecha(iso: string) {
  const [y, m, d] = iso.split("-");
  return `${d}/${m}/${y}`;
}

// ════════════════════════════════════════════════════════════
// PÁGINA PRINCIPAL
// ════════════════════════════════════════════════════════════
export default function MisTareasPage() {
  const { data: session } = useSession();
  const userName = (session?.user as { name?: string } | undefined)?.name ?? "";

  const { data: json, isLoading: loading, mutate: mutateData } = useApi<{ data: MisTareas }>("/api/mis-tareas");
  const data = json?.data ?? null;

  const autoRefresh = useAutoRefresh({
    onRefresh: () => { void mutateData(); },
  });

  // ── Calcular KPIs ─────────────────────────────────────────
  const kpis = data ? {
    total: data.novedades.length + data.guardados.length + data.guardadosTiendaPendientes.length + data.despachosTienda.length,
    vencidas: [
      ...data.novedades.filter((n) => calcSla(n.fechaCompromiso) === "VENCIDO"),
    ].length,
    proximas: [
      ...data.novedades.filter((n) => calcSla(n.fechaCompromiso) === "PROXIMO"),
      ...data.guardados.filter((g) => { const u = urgencia(g); return u?.tipo === "proxima"; }),
      ...data.despachosTienda.filter((d) => { if (!d.fechaEntregaComprometida) return false; return calcSla(d.fechaEntregaComprometida) === "PROXIMO"; }),
    ].length,
  } : { total: 0, vencidas: 0, proximas: 0 };

  const hora = new Date().getHours();
  const saludo = hora < 12 ? "Buenos dias" : hora < 18 ? "Buenas tardes" : "Buenas noches";

  return (
    <div className="animate-fade-in" style={{ ...getModuleCssVars("mis-tareas"), maxWidth: 720 } as React.CSSProperties}>
      <ModuleHero
        moduleKey="mis-tareas"
        kicker="Bandeja personal"
        title="Mis Tareas"
        description={`${saludo}${userName ? `, ${userName}` : ""} / ${new Date().toLocaleDateString("es-CO", { weekday: "long", day: "numeric", month: "long" })}`}
        actions={(
          <AutoRefreshIndicator
            lastUpdatedAt={autoRefresh.lastUpdatedAt}
            refreshing={autoRefresh.refreshing || loading}
            onRefresh={autoRefresh.refreshNow}
          />
        )}
      />

      {/* ── KPIs flotantes ── */}
      {!loading && data && (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 20, marginBottom: 28, padding: "0 2px" }}>
          <div className="ds-stat">
            <div className="ds-stat-value" style={{ color: "var(--text)" }}>{kpis.total}</div>
            <div className="ds-stat-label">Tareas pendientes</div>
          </div>
          <div className="ds-stat">
            <div className="ds-stat-value" style={{ color: kpis.vencidas > 0 ? "var(--error)" : "var(--muted)" }}>{kpis.vencidas}</div>
            <div className="ds-stat-label">SLA vencidas</div>
          </div>
          <div className="ds-stat">
            <div className="ds-stat-value" style={{ color: kpis.proximas > 0 ? "var(--warning)" : "var(--muted)" }}>{kpis.proximas}</div>
            <div className="ds-stat-label">Proximas a vencer</div>
          </div>
        </div>
      )}

      {loading ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {Array.from({ length: 5 }).map((_, i) => <div key={i} className="skeleton" style={{ height: 60, borderRadius: 10 }} />)}
        </div>
      ) : !data ? (
        <EmptyState icon={<CheckSquare size={22} />} title="Error al cargar" description="Intenta actualizar." />
      ) : (
        <>
          {/* ── INVENTARIO: Novedades ──────────────────────── */}
          {data.novedades.length > 0 && (
            <Seccion icon={<Package size={15} />} title="Novedades asignadas" count={data.novedades.length} color="var(--brand)">
              {data.novedades.slice(0, 10).map((n) => {
                const sla = calcSla(n.fechaCompromiso);
                const dias = diasRestantesSla(n.fechaCompromiso);
                return (
                  <TareaCard
                    key={n.id}
                    href="/dashboard/inventario"
                    titulo={`PLU ${n.plu} / ${n.posicion}`}
                    sub={n.fabricante ?? n.estado}
                    badge={n.fechaCompromiso ? (sla === "VENCIDO" ? `Vencido ${Math.abs(dias!)}d` : sla === "PROXIMO" ? `${dias}d restantes` : SLA_LABEL[sla]) : n.estado}
                    badgeColor={SLA_COLOR[sla]}
                    alerta={sla === "VENCIDO"}
                    tiempo={n.esPropio ? "mia" : n.asignadoA ?? undefined}
                  />
                );
              })}
              {data.novedades.length > 10 && <div style={{ fontSize: 12, color: "var(--muted)", textAlign: "center", padding: "8px 0" }}>+{data.novedades.length - 10} mas en <Link href="/dashboard/inventario" style={{ color: "var(--brand)" }}>Novedades</Link></div>}
            </Seccion>
          )}

          {/* ── TRANSPORTE: Guardados ─────────────────────── */}
          {data.guardados.length > 0 && (
            <Seccion icon={<Truck size={15} />} title="Guardados pendientes" count={data.guardados.length} color="var(--brand)">
              {data.guardados.slice(0, 8).map((g) => {
                const u = urgencia(g);
                const alerta = u?.tipo === "vencida";
                return (
                  <TareaCard
                    key={g.clientId}
                    href="/dashboard/transporte"
                    titulo={g.documento}
                    sub={`${g.ubicacion} / ${g.tipo ?? ""}`}
                    badge={alerta ? `Entrega vencida ${u!.dias}d` : u?.tipo === "proxima" ? `${u.dias}d para entrega` : "Pendiente"}
                    badgeColor={alerta ? "var(--error)" : u?.tipo === "proxima" ? "var(--warning)" : "var(--muted)"}
                    alerta={alerta}
                    tiempo={fmtFecha(g.fecha)}
                  />
                );
              })}
              {data.guardados.length > 8 && <div style={{ fontSize: 12, color: "var(--muted)", textAlign: "center", padding: "8px 0" }}>+{data.guardados.length - 8} mas en <Link href="/dashboard/transporte" style={{ color: "var(--brand)" }}>Transporte</Link></div>}
            </Seccion>
          )}

          {data.guardadosTiendaPendientes.length > 0 && (
            <Seccion icon={<Truck size={15} />} title="Despachos de tienda por guardar" count={data.guardadosTiendaPendientes.length} color="var(--brand)">
              {data.guardadosTiendaPendientes.slice(0, 8).map((p) => (
                <TareaCard
                  key={p.id}
                  href="/dashboard/transporte"
                  titulo={`${p.documento} / ${p.clienteNombre}`}
                  sub={`${p.centroCostos}${p.numeroCajas ? ` / ${p.numeroCajas} cajas` : ""}`}
                  badge="Pendiente por guardar"
                  badgeColor="var(--brand)"
                  tiempo={new Date(p.createdAt).toLocaleDateString("es-CO")}
                />
              ))}
            </Seccion>
          )}

          {/* ── TIENDA: Despachos pendientes ──────────────── */}
          {data.despachosTienda.length > 0 && (
            <Seccion icon={<Store size={15} />} title="Despachos tienda pendientes" count={data.despachosTienda.length} color="var(--brand)">
              {data.despachosTienda.slice(0, 8).map((d) => {
                const horas = horasDesde(d.createdAt);
                const critico = horas >= 24;
                const slaDespach = d.fechaEntregaComprometida ? calcSla(d.fechaEntregaComprometida) : null;
                return (
                  <TareaCard
                    key={d.id}
                    href="/dashboard/tienda"
                    titulo={`${d.numeroDocumento} / ${d.clienteNombre}`}
                    sub={`${d.centroCostos} / ${d.estado}`}
                    badge={critico ? `${horas}h pendiente` : slaDespach ? SLA_LABEL[slaDespach] : d.estado}
                    badgeColor={critico ? "var(--error)" : slaDespach ? SLA_COLOR[slaDespach] : "var(--muted)"}
                    alerta={critico || slaDespach === "VENCIDO"}
                    tiempo={fmtFecha(d.fechaCreacion)}
                  />
                );
              })}
              {data.despachosTienda.length > 8 && <div style={{ fontSize: 12, color: "var(--muted)", textAlign: "center", padding: "8px 0" }}>+{data.despachosTienda.length - 8} mas en <Link href="/dashboard/tienda" style={{ color: "var(--brand)" }}>Tienda</Link></div>}
            </Seccion>
          )}

          {/* Estado vacío total */}
          {kpis.total === 0 && (
            <EmptyState
              icon={<CheckSquare size={22} />}
              title="Todo al dia"
              description="No tienes tareas pendientes en este momento. Buen trabajo."
            />
          )}
        </>
      )}
    </div>
  );
}

// nuxt-app/pages/mis-tareas.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { CheckSquare, Package, Truck, Store, AlertTriangle, CheckCircle2, RefreshCw } from '@lucide/vue'
import { calcSla, diasRestantesSla, SLA_COLOR, SLA_LABEL, type SlaEstado } from '~/utils/sla'
import { urgencia } from '~/utils/guardado'
import { horasDesde } from '~/utils/despacho'
import { ensureSession, useSessionState } from '~/composables/useSession'
import { useAutoRefresh, formatLastUpdated } from '~/composables/useAutoRefresh'

definePageMeta({ title: 'Mis Tareas' })

const { me } = useSessionState()
const loading = ref(true)
const data = ref<MisTareas | null>(null)

interface TareaNovedad { id: string; plu: string; posicion: string; estado: string; fabricante: string | null; asignadoA: string | null; fechaCompromiso: string | null; esPropio: boolean }
interface TareaGuardado { id: string; clientId: string; documento: string; ubicacion: string; estado: string; fecha: string; nota: string | null; tipo: string | null }
interface TareaGuardadoTienda { id: string; despachoId: string; nota: string | null; createdAt: string; documento: string; clienteNombre: string; centroCostos: string; numeroCajas: number | null }
interface TareaDespacho { id: string; centroCostos: string; numeroDocumento: string; clienteNombre: string; estado: string; fechaCreacion: string; fechaEntregaComprometida: string | null; createdAt: string }
interface MisTareas { novedades: TareaNovedad[]; guardados: TareaGuardado[]; guardadosTiendaPendientes: TareaGuardadoTienda[]; despachosTienda: TareaDespacho[]; notifNoLeidas: number }

async function load() {
  try {
    const res = await $fetch<{ success: boolean; data: MisTareas }>('/api/mis-tareas')
    data.value = res.data
  } catch {
    data.value = null
  }
}

onMounted(async () => {
  ensureSession()
  await load()
  loading.value = false
})

const { refreshing, lastUpdatedAt, refreshNow } = useAutoRefresh({
  onRefresh: load,
})

async function refresh() {
  if (refreshing.value) return
  loading.value = true
  await load()
  loading.value = false
  void refreshNow()
}

const kpis = computed(() => {
  if (!data.value) return { total: 0, vencidas: 0, proximas: 0 }
  return {
    total: data.value.novedades.length + data.value.guardados.length + data.value.guardadosTiendaPendientes.length + data.value.despachosTienda.length,
    vencidas: data.value.novedades.filter((n) => calcSla(n.fechaCompromiso) === 'VENCIDO').length,
    proximas: [
      ...data.value.novedades.filter((n) => calcSla(n.fechaCompromiso) === 'PROXIMO'),
      ...data.value.guardados.filter((g) => { const u = urgencia(g); return u?.tipo === 'proxima' }),
      ...data.value.despachosTienda.filter((d) => { if (!d.fechaEntregaComprometida) return false; return calcSla(d.fechaEntregaComprometida) === 'PROXIMO' }),
    ].length,
  }
})

const hora = new Date().getHours()
const saludo = hora < 12 ? 'Buenos días' : hora < 18 ? 'Buenas tardes' : 'Buenas noches'
const userName = computed(() => me.value?.name ?? '')

function fmtFecha(iso: string) {
  const [y, m, d] = iso.split('-')
  return `${d}/${m}/${y}`
}
</script>

<template>
  <div class="page">
    <!-- Hero -->
    <section class="hero">
      <div class="hero-left">
        <div class="hero-kicker">Bandeja personal</div>
        <h1 class="hero-title">Mis Tareas</h1>
        <p class="hero-desc">{{ saludo }}{{ userName ? `, ${userName}` : '' }} / {{ new Date().toLocaleDateString('es-CO', { weekday: 'long', day: 'numeric', month: 'long' }) }}</p>
      </div>
      <div class="hero-actions">
        <button class="btn btn-sm refresh" :class="{ spin: refreshing || loading }" @click="refresh">
          <RefreshCw :size="14" />
          {{ refreshing || loading ? 'Actualizando…' : 'Actualizar' }}
        </button>
        <span class="hlp">{{ formatLastUpdated(lastUpdatedAt) }}</span>
      </div>
    </section>

    <!-- KPIs -->
    <div v-if="!loading && data" class="kpis">
      <div class="kpi">
        <div class="kpi-val">{{ kpis.total }}</div>
        <div class="kpi-lbl">Tareas pendientes</div>
      </div>
      <div class="kpi">
        <div class="kpi-val" :class="{ err: kpis.vencidas > 0 }">{{ kpis.vencidas }}</div>
        <div class="kpi-lbl">SLA vencidas</div>
      </div>
      <div class="kpi">
        <div class="kpi-val" :class="{ warn: kpis.proximas > 0 }">{{ kpis.proximas }}</div>
        <div class="kpi-lbl">Próximas a vencer</div>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="skels">
      <div v-for="i in 5" :key="i" class="skeleton" style="height:60px;border-radius:10px" />
    </div>

    <!-- Error -->
    <EmptyState v-else-if="!data" title="Error al cargar" description="Intenta actualizar.">
      <template #icon><CheckSquare :size="22" /></template>
    </EmptyState>

    <!-- Content -->
    <template v-else>
      <!-- Novedades -->
      <div v-if="data.novedades.length > 0" class="sec">
        <div class="sec-hd">
          <div class="sec-ic"><Package :size="15" /></div>
          <span class="sec-tt">Novedades asignadas</span>
          <span class="sec-cnt">{{ data.novedades.length }}</span>
        </div>
        <div class="sec-cards">
          <a v-for="n in data.novedades.slice(0, 10)" :key="n.id" href="/dashboard/inventario" class="card" :class="{ alerta: calcSla(n.fechaCompromiso) === 'VENCIDO' }">
            <AlertTriangle v-if="calcSla(n.fechaCompromiso) === 'VENCIDO'" :size="14" class="card-alert" />
            <div class="card-body">
              <div class="card-tit">PLU {{ n.plu }} / {{ n.posicion }}</div>
              <div v-if="n.fabricante" class="card-sub">{{ n.fabricante }}</div>
            </div>
            <div class="card-side">
              <span v-if="n.fechaCompromiso" class="card-bdg" :style="{ '--c': SLA_COLOR[calcSla(n.fechaCompromiso)] }">
                {{ (() => { const s = calcSla(n.fechaCompromiso); const d = diasRestantesSla(n.fechaCompromiso); return s === 'VENCIDO' ? `Vencido ${Math.abs(d!)}d` : s === 'PROXIMO' ? `${d}d restantes` : SLA_LABEL[s] })() }}
              </span>
              <span v-else class="card-bdg" :style="{ '--c': 'var(--muted)' }">{{ n.estado }}</span>
              <span class="card-tm">{{ n.esPropio ? 'mía' : n.asignadoA ?? '' }}</span>
            </div>
          </a>
          <div v-if="data.novedades.length > 10" class="sec-more">+{{ data.novedades.length - 10 }} más en <a href="/dashboard/inventario" class="sec-link">Novedades</a></div>
        </div>
      </div>

      <!-- Guardados pendientes -->
      <div v-if="data.guardados.length > 0" class="sec">
        <div class="sec-hd">
          <div class="sec-ic"><Truck :size="15" /></div>
          <span class="sec-tt">Guardados pendientes</span>
          <span class="sec-cnt">{{ data.guardados.length }}</span>
        </div>
        <div class="sec-cards">
          <a v-for="g in data.guardados.slice(0, 8)" :key="g.clientId" href="/dashboard/transporte" class="card" :class="{ alerta: urgencia(g)?.tipo === 'vencida' }">
            <AlertTriangle v-if="urgencia(g)?.tipo === 'vencida'" :size="14" class="card-alert" />
            <div class="card-body">
              <div class="card-tit">{{ g.documento }}</div>
              <div class="card-sub">{{ g.ubicacion }}{{ g.tipo ? ` / ${g.tipo}` : '' }}</div>
            </div>
            <div class="card-side">
              <span class="card-bdg" :style="{ '--c': urgencia(g)?.tipo === 'vencida' ? 'var(--error)' : urgencia(g)?.tipo === 'proxima' ? 'var(--warning)' : 'var(--muted)' }">
                {{ (() => { const u = urgencia(g); return u?.tipo === 'vencida' ? `Entrega vencida ${u.dias}d` : u?.tipo === 'proxima' ? `${u.dias}d para entrega` : 'Pendiente' })() }}
              </span>
              <span class="card-tm">{{ fmtFecha(g.fecha) }}</span>
            </div>
          </a>
          <div v-if="data.guardados.length > 8" class="sec-more">+{{ data.guardados.length - 8 }} más en <a href="/dashboard/transporte" class="sec-link">Transporte</a></div>
        </div>
      </div>

      <!-- Despachos tienda por guardar -->
      <div v-if="data.guardadosTiendaPendientes.length > 0" class="sec">
        <div class="sec-hd">
          <div class="sec-ic"><Truck :size="15" /></div>
          <span class="sec-tt">Despachos de tienda por guardar</span>
          <span class="sec-cnt">{{ data.guardadosTiendaPendientes.length }}</span>
        </div>
        <div class="sec-cards">
          <a v-for="p in data.guardadosTiendaPendientes.slice(0, 8)" :key="p.id" href="/dashboard/transporte" class="card">
            <div class="card-body">
              <div class="card-tit">{{ p.documento }} / {{ p.clienteNombre }}</div>
              <div class="card-sub">{{ p.centroCostos }}{{ p.numeroCajas ? ` / ${p.numeroCajas} cajas` : '' }}</div>
            </div>
            <div class="card-side">
              <span class="card-bdg" style="--c:var(--brand)">Pendiente por guardar</span>
              <span class="card-tm">{{ new Date(p.createdAt).toLocaleDateString('es-CO') }}</span>
            </div>
          </a>
          <div v-if="data.guardadosTiendaPendientes.length > 8" class="sec-more">+{{ data.guardadosTiendaPendientes.length - 8 }} más en <a href="/dashboard/transporte" class="sec-link">Transporte</a></div>
        </div>
      </div>

      <!-- Despachos tienda pendientes -->
      <div v-if="data.despachosTienda.length > 0" class="sec">
        <div class="sec-hd">
          <div class="sec-ic"><Store :size="15" /></div>
          <span class="sec-tt">Despachos tienda pendientes</span>
          <span class="sec-cnt">{{ data.despachosTienda.length }}</span>
        </div>
        <div class="sec-cards">
          <a v-for="d in data.despachosTienda.slice(0, 8)" :key="d.id" href="/dashboard/tienda" class="card" :class="{ alerta: horasDesde(d.createdAt) >= 24 || (d.fechaEntregaComprometida !== null && calcSla(d.fechaEntregaComprometida) === 'VENCIDO') }">
            <AlertTriangle v-if="horasDesde(d.createdAt) >= 24 || calcSla(d.fechaEntregaComprometida) === 'VENCIDO'" :size="14" class="card-alert" />
            <div class="card-body">
              <div class="card-tit">{{ d.numeroDocumento }} / {{ d.clienteNombre }}</div>
              <div class="card-sub">{{ d.centroCostos }} / {{ d.estado }}</div>
            </div>
            <div class="card-side">
              <span class="card-bdg" :style="{ '--c': horasDesde(d.createdAt) >= 24 ? 'var(--error)' : d.fechaEntregaComprometida ? SLA_COLOR[calcSla(d.fechaEntregaComprometida)] : 'var(--muted)' }">
                {{ horasDesde(d.createdAt) >= 24 ? `${horasDesde(d.createdAt)}h pendiente` : d.fechaEntregaComprometida ? SLA_LABEL[calcSla(d.fechaEntregaComprometida)] : d.estado }}
              </span>
              <span class="card-tm">{{ fmtFecha(d.fechaCreacion) }}</span>
            </div>
          </a>
          <div v-if="data.despachosTienda.length > 8" class="sec-more">+{{ data.despachosTienda.length - 8 }} más en <a href="/dashboard/tienda" class="sec-link">Tienda</a></div>
        </div>
      </div>

      <!-- Empty -->
      <EmptyState v-if="kpis.total === 0" title="Todo al día" description="No tienes tareas pendientes en este momento. Buen trabajo.">
        <template #icon><CheckSquare :size="22" /></template>
      </EmptyState>
    </template>
  </div>
</template>

<style scoped>
.page { max-width: 720px; }
.hero { display: flex; align-items: flex-end; justify-content: space-between; gap: 18px; margin-bottom: 22px; flex-wrap: wrap; }
.hero::before { content: ''; position: absolute; left: -40px; top: -30px; width: 260px; height: 120px; background: radial-gradient(closest-side, color-mix(in srgb, var(--brand) 16%, transparent), transparent); pointer-events: none; z-index: -1; }
.hero-kicker { display: inline-flex; align-items: center; gap: 6px; font-size: 11px; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; color: var(--brand-deep); }
.hero-kicker::before { content: ''; width: 14px; height: 2px; border-radius: 2px; background: var(--brand); }
.hero-title { font-size: 28px; font-weight: 800; letter-spacing: -.03em; margin: 4px 0 0; }
.hero-desc { font-size: 13.5px; color: var(--muted); margin: 5px 0 0; }
.hero-actions { display: flex; align-items: center; gap: 9px; flex-wrap: wrap; }
.hlp { font-size: 11px; color: var(--faint); font-weight: 500; }
.refresh.spin :deep(svg) { animation: spin .8s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }

/* KPIs */
.kpis { display: grid; grid-template-columns: repeat(3,1fr); gap: 20px; margin-bottom: 28px; }
.kpi { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 14px 16px; }
.kpi-val { font-size: 24px; font-weight: 800; font-family: var(--mono); letter-spacing: -.03em; color: var(--ink); }
.kpi-val.err { color: var(--error); }
.kpi-val.warn { color: var(--warning); }
.kpi-lbl { font-size: 12px; color: var(--muted); margin-top: 2px; font-weight: 500; }

/* Sections */
.sec { margin-bottom: 20px; }
.sec-hd { display: flex; align-items: center; gap: 8px; margin-bottom: 10px; }
.sec-ic { width: 28px; height: 28px; border-radius: 7px; background: color-mix(in srgb, var(--brand) 14%, transparent); display: grid; place-items: center; color: var(--brand); }
.sec-tt { font-size: 13px; font-weight: 700; color: var(--ink); }
.sec-cnt { font-size: 12px; font-weight: 700; padding: 1px 8px; border-radius: 20px; background: var(--surface-3); color: var(--muted); font-family: var(--mono); }
.sec-cards { display: flex; flex-direction: column; gap: 6px; }
.sec-more { font-size: 12px; color: var(--muted); text-align: center; padding: 8px 0; }
.sec-link { color: var(--brand); text-decoration: none; font-weight: 600; }
.sec-link:hover { text-decoration: underline; }

/* Card */
.card { display: flex; align-items: flex-start; gap: 12px; padding: 12px 16px; background: var(--surface); border: 1px solid var(--border); border-radius: 10px; transition: box-shadow .12s; cursor: pointer; text-decoration: none; }
.card:hover { box-shadow: var(--shadow-md); }
.card.alerta { border-color: color-mix(in srgb, var(--error) 30%, transparent); }
.card-alert { flex-shrink: 0; margin-top: 2px; color: var(--error); }
.card-body { flex: 1; min-width: 0; }
.card-tit { font-size: 13px; font-weight: 600; color: var(--ink); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.card-sub { font-size: 11px; color: var(--muted); margin-top: 2px; }
.card-side { display: flex; flex-direction: column; align-items: flex-end; gap: 4px; flex-shrink: 0; }
.card-bdg { font-size: 10px; font-weight: 700; padding: 2px 7px; border-radius: 20px; background: color-mix(in srgb, var(--c) 18%, transparent); color: var(--c); }
.card-tm { font-size: 10px; color: var(--faint); font-family: var(--mono); }

/* Loading */
.skels { display: flex; flex-direction: column; gap: 8px; }
</style>
