// nuxt-app/app/components/cargue-gourmet/CierreManualModal.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { PedidoGourmet } from '~/utils/gourmet'

const props = defineProps<{ p: PedidoGourmet; saving?: boolean }>()
const emit = defineEmits<{ (e: 'close'): void; (e: 'saved', payload: Record<string, unknown>): void }>()

const cantidadContadaManual = ref('')
const error = ref('')

function submit() {
  error.value = ''
  const cantidad = parseInt(cantidadContadaManual.value, 10)
  if (!Number.isInteger(cantidad) || cantidad < 0) {
    error.value = 'La cantidad contada debe ser un entero mayor o igual a 0'
    return
  }
  emit('saved', { cantidadContadaManual: cantidad, updatedAt: props.p.updatedAt })
}
</script>

<template>
  <ModalShell title="Cierre manual de contingencia" sub="Documenta una excepción operativa del cargue" @close="emit('close')">
    <form class="form" @submit.prevent="submit">
      <div class="advertencia">
        Este cierre documenta una contingencia operativa. Solo debe usarse cuando el cargue no puede finalizarse normalmente.
        El motivo se registra automáticamente como "TIEMPO".
      </div>

      <label class="fw">
        <span class="fl">Cantidad contada manualmente</span>
        <input v-model="cantidadContadaManual" type="number" min="0" class="field">
      </label>

      <p v-if="error" class="err-msg">{{ error }}</p>

      <div class="factions">
        <button type="button" class="btn" :disabled="saving" @click="emit('close')">Cancelar</button>
        <button type="submit" class="btn btn-danger" :disabled="saving">
          <Spinner v-if="saving" />{{ saving ? 'Cerrando…' : 'Cerrar manualmente' }}
        </button>
      </div>
    </form>
  </ModalShell>
</template>

<style scoped>
.form { display: flex; flex-direction: column; gap: 14px; }
.advertencia { font-size: 13px; color: var(--u-aviso); background: var(--u-aviso-tint); border: 1px solid var(--u-aviso); border-radius: var(--r-sm); padding: 10px 12px; }
.fw { display: flex; flex-direction: column; gap: 5px; }
.fl { font-size: 12px; font-weight: 600; color: var(--ink-2); }
.err-msg { font-size: 12px; color: var(--u-critico); margin: 0; }
.factions { display: grid; grid-template-columns: 1fr 2fr; gap: 10px; padding-top: 6px; }
.factions .btn { justify-content: center; }
</style>

// src/app/(dashboard)/dashboard/cargue-gourmet/_components/CierreManualModal.tsx
"use client";

import { useEffect, useState } from "react";
import { Modal } from "@/components/ui/Modal";
import { useToast } from "@/contexts/ToastContext";
import { apiPost } from "@/lib/apiClient";
import { getErrorMessage } from "@/lib/errors";

export interface PedidoCerrable {
  id: string;
  updatedAt: string;
}

function emptyForm() {
  return { cantidadContadaManual: "" };
}

const label: React.CSSProperties = {
  fontSize: 12, fontWeight: 500, color: "var(--muted2)", display: "block", marginBottom: 5,
};
const inp: React.CSSProperties = {
  width: "100%", height: 36, padding: "0 12px",
  background: "var(--surface2)", border: "1px solid var(--border)",
  borderRadius: 8, fontSize: 14, fontFamily: "var(--sans)",
  color: "var(--text)", outline: "none",
};

export function CierreManualModal({
  open,
  pedido,
  onClose,
  onClosed,
}: {
  open: boolean;
  pedido: PedidoCerrable | null;
  onClose: () => void;
  onClosed: () => void;
}) {
  const toast = useToast();
  const [form, setForm] = useState(emptyForm());
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (open) {
      setForm(emptyForm());
      setError("");
    }
  }, [open]);

  function handleClose() {
    if (saving) return;
    onClose();
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (saving || !pedido) return;
    setError("");

    const cantidad = parseInt(form.cantidadContadaManual, 10);
    if (!Number.isInteger(cantidad) || cantidad < 0) {
      setError("La cantidad contada debe ser un entero mayor o igual a 0");
      return;
    }

    setSaving(true);
    try {
      // 409 aquí puede ser: el pedido ya no está EN_CARGUE/CON_NOVEDAD, ya fue
      // cerrado, updatedAt desactualizado, o no hay cargue válido — se muestra
      // siempre el mensaje real del backend, sin asumir cuál caso.
      await apiPost(`/api/cargue-gourmet/${pedido.id}/cierre-manual`, {
        cantidadContadaManual: cantidad,
        updatedAt: pedido.updatedAt,
      });
      toast.success("Cargue cerrado manualmente");
      onClosed();
      onClose();
    } catch (e) {
      setError(getErrorMessage(e, "No se pudo cerrar manualmente el cargue"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal
      open={open}
      onClose={handleClose}
      title="Cierre manual de contingencia"
      subtitle="Documenta una excepción operativa del cargue"
      footer={
        <>
          <button type="button" onClick={handleClose} className="g-btn g-btn-ghost" disabled={saving}>Cancelar</button>
          <button type="submit" form="cierre-manual-form" className="g-btn g-btn-danger" disabled={saving}>
            {saving ? "Cerrando…" : "Cerrar manualmente"}
          </button>
        </>
      }
    >
      <form id="cierre-manual-form" onSubmit={submit} style={{ display: "flex", flexDirection: "column", gap: 14 }}>
        <div
          data-testid="cierre-manual-advertencia"
          style={{ fontSize: 13, color: "var(--warning)", background: "var(--warning-tint, rgba(255,196,61,0.12))", border: "1px solid var(--warning)", borderRadius: 8, padding: "10px 12px" }}
        >
          Este cierre documenta una contingencia operativa. Solo debe usarse cuando el cargue no puede finalizarse normalmente.
          El motivo se registra automáticamente como &quot;TIEMPO&quot;.
        </div>

        <div>
          <label style={label}>Cantidad contada manualmente</label>
          <input
            type="number" min={0} required
            value={form.cantidadContadaManual}
            onChange={(e) => setForm((f) => ({ ...f, cantidadContadaManual: e.target.value }))}
            style={inp}
            data-testid="cierre-manual-cantidad-input"
          />
        </div>

        {error && <p style={{ fontSize: 13, color: "var(--error)", margin: 0 }} data-testid="cierre-manual-error">{error}</p>}
      </form>
    </Modal>
  );
}
