// nuxt-app/app/components/cargue-gourmet/EditarPedidoModal.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { PedidoGourmet } from '~/utils/gourmet'

interface TiendaOption { codigo: string; tienda: string; ciudad: string }

const props = defineProps<{ p: PedidoGourmet; saving?: boolean }>()
const emit = defineEmits<{ (e: 'close'): void; (e: 'saved', payload: Record<string, unknown>): void }>()

const orden = ref(props.p.orden)
const codigoTiendaQuery = ref(props.p.codigoTienda)
const tiendaSeleccionada = ref<TiendaOption | null>({ codigo: props.p.codigoTienda, tienda: props.p.nombreTienda, ciudad: props.p.ciudadDestino })
const cajasEsperadas = ref(String(props.p.cajasEsperadas))
const estibasEsperadas = ref(String(props.p.estibasEsperadas))
const error = ref('')

const suggestions = ref<TiendaOption[]>([])
const searchLoading = ref(false)
const showSuggestions = ref(false)
let debounceTimer: ReturnType<typeof setTimeout> | null = null

function onCodigoTiendaInput(value: string) {
  if (debounceTimer) clearTimeout(debounceTimer)
  codigoTiendaQuery.value = value
  tiendaSeleccionada.value = null
  if (value.trim().toUpperCase() === 'CLIENTE') {
    tiendaSeleccionada.value = { codigo: 'CLIENTE', tienda: 'Cliente final', ciudad: 'CLIENTE' }
    showSuggestions.value = false
    return
  }
  showSuggestions.value = true
  if (!value.trim()) { suggestions.value = []; return }
  debounceTimer = setTimeout(async () => {
    searchLoading.value = true
    try {
      const res = await $fetch<{ data: TiendaOption[] }>(`/api/cargue-gourmet/maestro-tiendas?q=${encodeURIComponent(value.trim())}`)
      suggestions.value = res.data ?? []
    } catch { suggestions.value = [] }
    finally { searchLoading.value = false }
  }, 250)
}
function selectTienda(t: TiendaOption) { codigoTiendaQuery.value = t.codigo; tiendaSeleccionada.value = t; showSuggestions.value = false }

function submit() {
  error.value = ''
  if (!orden.value.trim()) { error.value = 'La orden es obligatoria'; return }
  if (!tiendaSeleccionada.value) { error.value = 'Selecciona una tienda válida de la lista'; return }
  const cajas = parseInt(cajasEsperadas.value, 10)
  if (!Number.isInteger(cajas) || cajas <= 0) { error.value = 'Cajas esperadas debe ser un entero mayor a 0'; return }
  const estibas = parseInt(estibasEsperadas.value, 10)
  if (!Number.isInteger(estibas) || estibas <= 0) { error.value = 'Estibas esperadas debe ser un entero mayor a 0'; return }

  emit('saved', {
    orden: orden.value.trim(),
    codigoTienda: tiendaSeleccionada.value.codigo,
    cajasEsperadas: cajas,
    estibasEsperadas: estibas,
    updatedAt: props.p.updatedAt,
  })
}
</script>

<template>
  <ModalShell title="Editar pedido Gourmet" :sub="`${p.tipoOrden} ${p.orden}`" wide @close="emit('close')">
    <form class="form" @submit.prevent="submit">
      <label class="fw"><span class="fl">Orden <b>*</b></span><input v-model="orden" class="field" maxlength="100"></label>

      <div class="fw autocomplete">
        <span class="fl">Código tienda <b>*</b></span>
        <input :value="codigoTiendaQuery" class="field" autocomplete="off" @input="onCodigoTiendaInput(($event.target as HTMLInputElement).value)" @focus="showSuggestions = true">
        <div v-if="showSuggestions && codigoTiendaQuery && !tiendaSeleccionada" class="suggestions">
          <div v-if="searchLoading" class="sugg-item faint">Buscando…</div>
          <div v-else-if="suggestions.length === 0" class="sugg-item faint">Sin coincidencias</div>
          <button v-for="t in suggestions" :key="t.codigo" type="button" class="sugg-item" @click="selectTienda(t)">
            <strong>{{ t.codigo }}</strong> — {{ t.tienda }} <span class="faint">({{ t.ciudad }})</span>
          </button>
        </div>
        <div v-if="tiendaSeleccionada" class="tienda-resuelta">{{ tiendaSeleccionada.tienda }} — {{ tiendaSeleccionada.ciudad }}</div>
      </div>

      <div class="g2">
        <label class="fw"><span class="fl">Cajas esperadas <b>*</b></span><input v-model="cajasEsperadas" type="number" min="1" class="field"></label>
        <label class="fw"><span class="fl">Estibas esperadas <b>*</b></span><input v-model="estibasEsperadas" type="number" min="1" class="field"></label>
      </div>

      <p v-if="error" class="err-msg">{{ error }}</p>

      <div class="factions">
        <button type="button" class="btn" :disabled="saving" @click="emit('close')">Cancelar</button>
        <button type="submit" class="btn btn-primary" :disabled="saving">
          <Spinner v-if="saving" />{{ saving ? 'Guardando…' : 'Guardar cambios' }}
        </button>
      </div>
    </form>
  </ModalShell>
</template>

<style scoped>
.form { display: flex; flex-direction: column; gap: 14px; }
.fw { display: flex; flex-direction: column; gap: 5px; position: relative; }
.fl { font-size: 12px; font-weight: 600; color: var(--ink-2); }
.fl b { color: var(--u-critico); font-weight: 700; }
.g2 { display: grid; grid-template-columns: 1fr 1fr; gap: 11px; }
.autocomplete { position: relative; }
.suggestions { position: absolute; z-index: 20; top: 100%; left: 0; right: 0; margin-top: 4px; background: var(--surface); border: 1px solid var(--border); border-radius: var(--r-sm); max-height: 200px; overflow-y: auto; box-shadow: var(--shadow-md); }
.sugg-item { display: block; width: 100%; text-align: left; padding: 8px 12px; background: none; border: none; cursor: pointer; font-size: 13px; color: var(--ink-2); }
.sugg-item:hover { background: var(--surface-2); }
.tienda-resuelta { font-size: 12px; color: var(--muted); margin-top: 4px; }
.faint { color: var(--faint); font-size: 12px; }
.err-msg { font-size: 12px; color: var(--u-critico); margin: 0; }
.factions { display: grid; grid-template-columns: 1fr 2fr; gap: 10px; padding-top: 6px; }
.factions .btn { justify-content: center; }
@media (max-width: 560px) { .g2 { grid-template-columns: 1fr; } }
</style>

// src/app/(dashboard)/dashboard/cargue-gourmet/_components/EditarPedidoModal.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { Modal } from "@/components/ui/Modal";
import { useToast } from "@/contexts/ToastContext";
import { apiGet, apiPut } from "@/lib/apiClient";
import { getErrorMessage } from "@/lib/errors";

const SEARCH_DEBOUNCE_MS = 250;

interface TiendaOption {
  codigo: string;
  tienda: string;
  ciudad: string;
}

export interface PedidoEditable {
  id: string;
  orden: string;
  tipoOrden: string;
  codigoTienda: string;
  nombreTienda: string;
  ciudadDestino: string;
  cajasEsperadas: number;
  estibasEsperadas: number;
  updatedAt: string;
}

const inp: React.CSSProperties = {
  width: "100%", height: 36, padding: "0 12px",
  background: "var(--surface2)", border: "1px solid var(--border)",
  borderRadius: 8, fontSize: 14, fontFamily: "var(--sans)",
  color: "var(--text)", outline: "none",
};

const label: React.CSSProperties = {
  fontSize: 12, fontWeight: 500, color: "var(--muted2)", display: "block", marginBottom: 5,
};

function formFromPedido(p: PedidoEditable | null) {
  return {
    orden: p?.orden ?? "",
    codigoTiendaQuery: p?.codigoTienda ?? "",
    tiendaSeleccionada: p ? { codigo: p.codigoTienda, tienda: p.nombreTienda, ciudad: p.ciudadDestino } as TiendaOption : null,
    cajasEsperadas: p ? String(p.cajasEsperadas) : "",
    estibasEsperadas: p ? String(p.estibasEsperadas) : "",
  };
}

export function EditarPedidoModal({
  open,
  pedido,
  onClose,
  onUpdated,
}: {
  open: boolean;
  pedido: PedidoEditable | null;
  onClose: () => void;
  onUpdated: () => void;
}) {
  const toast = useToast();
  const [form, setForm] = useState(formFromPedido(pedido));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const [suggestions, setSuggestions] = useState<TiendaOption[]>([]);
  const [searchLoading, setSearchLoading] = useState(false);
  const [searchError, setSearchError] = useState("");
  const [showSuggestions, setShowSuggestions] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (open) {
      setForm(formFromPedido(pedido));
      setError("");
      setSuggestions([]);
      setShowSuggestions(false);
    }
  }, [open, pedido]);

  function handleClose() {
    if (saving) return;
    onClose();
  }

  function onCodigoTiendaChange(value: string) {
    setForm((f) => ({ ...f, codigoTiendaQuery: value, tiendaSeleccionada: null }));
    setShowSuggestions(true);

    if (debounceRef.current) clearTimeout(debounceRef.current);
    if (!value.trim()) {
      setSuggestions([]);
      return;
    }
    debounceRef.current = setTimeout(async () => {
      setSearchLoading(true);
      setSearchError("");
      try {
        const json = await apiGet<{ data?: TiendaOption[] }>(`/api/cargue-gourmet/maestro-tiendas?q=${encodeURIComponent(value.trim())}`);
        setSuggestions(json.data ?? []);
      } catch {
        setSearchError("No se pudo buscar tiendas");
        setSuggestions([]);
      } finally {
        setSearchLoading(false);
      }
    }, SEARCH_DEBOUNCE_MS);
  }

  function selectTienda(t: TiendaOption) {
    setForm((f) => ({ ...f, codigoTiendaQuery: t.codigo, tiendaSeleccionada: t }));
    setShowSuggestions(false);
    setSuggestions([]);
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (saving || !pedido) return;
    setError("");

    if (!form.orden.trim()) { setError("La orden es obligatoria"); return; }
    if (!form.tiendaSeleccionada) { setError("Selecciona una tienda válida de la lista"); return; }
    const cajas = parseInt(form.cajasEsperadas, 10);
    if (!Number.isInteger(cajas) || cajas <= 0) { setError("Cajas esperadas debe ser un entero mayor a 0"); return; }
    const estibas = parseInt(form.estibasEsperadas, 10);
    if (!Number.isInteger(estibas) || estibas <= 0) { setError("Estibas esperadas debe ser un entero mayor a 0"); return; }

    setSaving(true);
    try {
      await apiPut(`/api/cargue-gourmet/${pedido.id}`, {
        orden: form.orden.trim(),
        codigoTienda: form.tiendaSeleccionada.codigo,
        cajasEsperadas: cajas,
        estibasEsperadas: estibas,
        updatedAt: pedido.updatedAt,
      });
      toast.success("Pedido actualizado");
      onUpdated();
      onClose();
    } catch (e) {
      setError(getErrorMessage(e, "No se pudo guardar la edición"));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal
      open={open}
      onClose={handleClose}
      title="Editar pedido Gourmet"
      subtitle={pedido ? `${pedido.tipoOrden} ${pedido.orden}` : undefined}
      footer={
        <>
          <button type="button" onClick={handleClose} className="g-btn g-btn-ghost" disabled={saving}>Cancelar</button>
          <button type="submit" form="editar-pedido-gourmet-form" className="g-btn g-btn-primary" disabled={saving}>
            {saving ? "Guardando…" : "Guardar cambios"}
          </button>
        </>
      }
    >
      <form id="editar-pedido-gourmet-form" onSubmit={submit} style={{ display: "flex", flexDirection: "column", gap: 14 }}>
        <div>
          <label style={label}>Orden</label>
          <input
            required
            value={form.orden}
            onChange={(e) => setForm((f) => ({ ...f, orden: e.target.value }))}
            maxLength={100}
            style={inp}
            data-testid="editar-orden-input"
          />
        </div>

        <div style={{ position: "relative" }}>
          <label style={label}>Código tienda</label>
          <input
            value={form.codigoTiendaQuery}
            onChange={(e) => onCodigoTiendaChange(e.target.value)}
            onFocus={() => setShowSuggestions(true)}
            placeholder="Buscar por código, tienda o ciudad…"
            style={inp}
            data-testid="editar-codigo-tienda-input"
            autoComplete="off"
          />
          {showSuggestions && form.codigoTiendaQuery && !form.tiendaSeleccionada && (
            <div
              data-testid="editar-tienda-suggestions"
              style={{
                position: "absolute", zIndex: 20, top: "100%", left: 0, right: 0, marginTop: 4,
                background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 8,
                maxHeight: 200, overflowY: "auto", boxShadow: "var(--shadow-md)",
              }}
            >
              {searchLoading && <div style={{ padding: "8px 12px", fontSize: 12, color: "var(--muted)" }}>Buscando…</div>}
              {!searchLoading && searchError && <div style={{ padding: "8px 12px", fontSize: 12, color: "var(--error)" }}>{searchError}</div>}
              {!searchLoading && !searchError && suggestions.length === 0 && (
                <div style={{ padding: "8px 12px", fontSize: 12, color: "var(--muted)" }}>Sin coincidencias</div>
              )}
              {!searchLoading && suggestions.map((t) => (
                <button
                  type="button"
                  key={t.codigo}
                  data-testid={`editar-tienda-option-${t.codigo}`}
                  onClick={() => selectTienda(t)}
                  style={{ display: "block", width: "100%", textAlign: "left", padding: "8px 12px", background: "none", border: "none", cursor: "pointer", fontSize: 13, color: "var(--text)" }}
                >
                  <strong>{t.codigo}</strong> — {t.tienda} <span style={{ color: "var(--muted)" }}>({t.ciudad})</span>
                </button>
              ))}
            </div>
          )}
          {form.tiendaSeleccionada && (
            <div data-testid="editar-tienda-resuelta" style={{ marginTop: 6, fontSize: 12, color: "var(--muted2)" }}>
              {form.tiendaSeleccionada.tienda} — {form.tiendaSeleccionada.ciudad}
            </div>
          )}
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
          <div>
            <label style={label}>Cajas esperadas</label>
            <input
              type="number" min={1} required
              value={form.cajasEsperadas}
              onChange={(e) => setForm((f) => ({ ...f, cajasEsperadas: e.target.value }))}
              style={inp}
              data-testid="editar-cajas-esperadas-input"
            />
          </div>
          <div>
            <label style={label}>Estibas esperadas</label>
            <input
              type="number" min={1} required
              value={form.estibasEsperadas}
              onChange={(e) => setForm((f) => ({ ...f, estibasEsperadas: e.target.value }))}
              style={inp}
              data-testid="editar-estibas-esperadas-input"
            />
          </div>
        </div>

        {error && <p style={{ fontSize: 13, color: "var(--error)", margin: 0 }} data-testid="editar-pedido-error">{error}</p>}
      </form>
    </Modal>
  );
}
